#!/usr/bin/env ruby

require 'json'

if ARGV.empty?
  # if no argument exit
  exec("echo no option specified && exit")
end


list_clusters = %x(aws ecs list-clusters)
list_clusters = %x(aws ecs describe-clusters)

case cmd
  # resolve commands to run
  when 'db'
    
  when 'help'
    puts 'help, db, cache, test'
    
  else
    puts "'#{File.basename(__FILE__)} #{cmd}' is not a valid command."
end



